from __future__ import annotations

import argparse
import csv
import os
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot static simulation loads per card over time")
    parser.add_argument(
        "csv_paths",
        type=Path,
        nargs="+",
        help="Path(s) to *_loads_*.csv file(s) generated by simulation",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory for plots. If omitted, plots saved to plot/ directory.",
    )
    parser.add_argument(
        "--format",
        type=str,
        default="pdf",
        choices=["pdf", "png"],
        help="Output format: pdf (default) or png",
    )
    return parser.parse_args()


# High-contrast palette
COLORS = ["#0b3c5d", "#b22222", "#2f4f4f", "#5e35b1", "#006400", "#ff8c00"]
# Use available fonts first to avoid warnings; prefer DejaVu (bundled with matplotlib)
plt.rcParams["font.family"] = ["DejaVu Sans", "DejaVu Serif", "sans-serif"]


def load_data(csv_path: Path):
    per_card_times: dict[int, list[int]] = defaultdict(list)
    per_card_loads: dict[int, list[float]] = defaultdict(list)
    per_card_tasks: dict[int, list[int]] = defaultdict(list)

    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            t = int(row["time_step"])
            card_id = int(row["card_id"])
            load = float(row["load"])
            task_cnt = int(row["tasks"])
            per_card_times[card_id].append(t)
            per_card_loads[card_id].append(load)
            per_card_tasks[card_id].append(task_cnt)

    return per_card_times, per_card_loads, per_card_tasks


def _compute_diff(per_card_times, per_card_loads, c0: int = 0, c1: int = 1):
    if c0 not in per_card_loads or c1 not in per_card_loads:
        return [], []

    m0 = dict(zip(per_card_times[c0], per_card_loads[c0]))
    m1 = dict(zip(per_card_times[c1], per_card_loads[c1]))
    common = sorted(set(m0.keys()) & set(m1.keys()))
    diffs = [abs(m0[t] - m1[t]) for t in common]
    return common, diffs


def _compute_avg(per_card_times, per_card_loads):
    times = sorted({t for ts in per_card_times.values() for t in ts})
    avg_by_time = {}
    for t in times:
        vals = []
        for cid, loads in per_card_loads.items():
            time_map = dict(zip(per_card_times[cid], loads))
            if t in time_map:
                vals.append(time_map[t])
        if vals:
            avg_by_time[t] = sum(vals) / len(vals)
    return avg_by_time


def _compute_variance(per_card_times, per_card_loads):
    """Compute load variance across cards for each time step."""
    times = sorted({t for ts in per_card_times.values() for t in ts})
    variance_by_time = {}
    for t in times:
        vals = []
        for cid, loads in per_card_loads.items():
            time_map = dict(zip(per_card_times[cid], loads))
            if t in time_map:
                vals.append(time_map[t])
        if len(vals) >= 2:
            mean = sum(vals) / len(vals)
            variance = sum((v - mean) ** 2 for v in vals) / len(vals)
            variance_by_time[t] = variance
        elif vals:
            variance_by_time[t] = 0.0
    return variance_by_time


def _setup_axes(ax, title: str, y_label: str):
   # ax.set_title(title)
    ax.set_xlabel("Time Step")
    ax.set_ylabel(y_label)
    ax.grid(True, alpha=0.3)
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))


def plot(per_card_times, per_card_loads, per_card_tasks, output: Path, format: str = "pdf"):
    output.parent.mkdir(parents=True, exist_ok=True)
    
    # Ensure output has correct extension
    output = output.with_suffix(f".{format}")

    card_items = sorted(per_card_loads.items())
    card_count = len(card_items)

    # Main load plot, variance plot, plus one small subplot per card
    height_ratios = [3, 1.5] + [1.1] * card_count
    fig, axes = plt.subplots(
        card_count + 2,
        1,
        figsize=(10, 5.5 + 1.2 * card_count),
        height_ratios=height_ratios,
        sharex=True,
    )
    ax_main = axes[0]
    ax_variance = axes[1]
    
    for idx, (card_id, loads) in enumerate(card_items):
        times = per_card_times[card_id]
        ax_main.plot(times, loads, label=f"Card {card_id} load", color=COLORS[idx % len(COLORS)])
    _setup_axes(ax_main, "Static Simulation Load per Card", "Load")
    ax_main.legend(frameon=False, loc="upper center", bbox_to_anchor=(0.5, 1.1), ncol=3)
    ax_main.set_xlabel("")

    # Plot load variance per step
    variance_by_time = _compute_variance(per_card_times, per_card_loads)
    times_var = sorted(variance_by_time.keys())
    variances = [variance_by_time[t] for t in times_var]
    ax_variance.fill_between(times_var, variances, alpha=0.3, color="#b22222")
    ax_variance.plot(times_var, variances, color="#b22222", linewidth=1.5, label="Load Variance")
    avg_var = sum(variances) / len(variances) if variances else 0
    ax_variance.axhline(avg_var, color="#555", linestyle="--", linewidth=1.0, label=f"Avg Variance: {avg_var:.2f}")
    _setup_axes(ax_variance, "Load Variance per Step", "Variance")
    ax_variance.legend(frameon=False, loc="upper right")
    ax_variance.set_xlabel("")

    avg_by_time = _compute_avg(per_card_times, per_card_loads)
    times_avg = sorted(avg_by_time.keys()) if avg_by_time else []
    for idx, (card_id, loads) in enumerate(card_items):
        ax_diff = axes[idx + 2]
        _setup_axes(ax_diff, f"Card {card_id} Δ to Avg", "Load - Avg")
        if idx < card_count - 1:
            ax_diff.set_xlabel("")

        if times_avg:
            time_map = dict(zip(per_card_times[card_id], loads))
            diffs = []
            times = []
            for t in times_avg:
                if t in time_map:
                    times.append(t)
                    diffs.append(time_map[t] - avg_by_time[t])
            if times:
                ax_diff.plot(times, diffs, color=COLORS[idx % len(COLORS)], label=f"Card {card_id} - avg")
        ax_diff.axhline(0.0, color="#555", linestyle="--", linewidth=1.0, label="Average load")
        ax_diff.legend(frameon=False, loc="upper right")

    fig.tight_layout()
    fig.savefig(output, dpi=150 if format == "png" else 100)
    plt.close(fig)

    task_output = output.with_name(output.stem + "_tasks" + output.suffix)
    fig, ax = plt.subplots(figsize=(10, 4))
    for idx, (card_id, tasks) in enumerate(sorted(per_card_tasks.items())):
        times = per_card_times[card_id]
        ax.plot(times, tasks, label=f"Card {card_id} tasks", color=COLORS[idx % len(COLORS)])
    _setup_axes(ax, "Static Simulation Tasks per Card", "Tasks")
    ax.legend(frameon=False, loc="upper center", bbox_to_anchor=(0.5, 1.15), ncol=3)
    fig.tight_layout()
    fig.savefig(task_output, dpi=150 if format == "png" else 100)
    plt.close(fig)

    return output, task_output


def main() -> None:
    args = parse_args()
    
    output_dir = args.output if args.output else Path("plot")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    for csv_path in args.csv_paths:
        if not csv_path.exists():
            print(f"Skipping {csv_path}: file not found")
            continue
            
        per_card_times, per_card_loads, per_card_tasks = load_data(csv_path)
        
        output = output_dir / f"{csv_path.stem}.{args.format}"
        load_file, tasks_file = plot(per_card_times, per_card_loads, per_card_tasks, output, format=args.format)
        print(f"Saved load plot to {load_file}")
        print(f"Saved tasks plot to {tasks_file}")


if __name__ == "__main__":
    main()
